const arabic = [
  {char: 'ا', english: 'a', ipa:'a'},
  {char: 'ىى / ى', english: 'short a', ipa:'short_a'},
  {char: 'و', english: 'o/u',ipa:'u'},
  {char: 'يي / ي', english: 'i',ipa:'i'},
  {char:'ههه / ه', english: 'h',ipa:'h'},
  {char: 'ة', english: 'short e',ipa:'short_e'},
  {char: 'ء / أ', english: 'first h in uh-oh', ipa:'ʔ'},
  {char: 'ببب / ب', english: 'b',ipa:'b'},
  {char: 'تتت / ت', english: 't', ipa:'t'},
  {char: 'ثثث / ث', english: 'th', ipa:'θ'},
  {char: 'ننن / ن', english: 'n',ipa:'n'},
  {char: 'ٖسس / س', english: 's', ipa:'s'},
  {char: 'شش / ش', english: 'sh',ipa:'sh'},
  {char: 'حح / ح', english: 'hard h', ipa:'ɦ'},
  {char: 'خخ / خ', english: 'kh', ipa:'x'},
  {char: 'جج / ج', english: 'j', ipa:'dʒ'},
  {char: 'مم / م', english: 'm', ipa:'m'},
  {char: 'فف / ف', english: 'f', ipa:'f'},
  {char: 'قق / ق', english: 'gh', ipa:'ʁ'},
  {char: 'كك / ك', english: 'k', ipa:'k'},
  {char: 'لل / ل', english: 'l', ipa:'l'},
  {char: 'ر', english: 'r', ipa:'r'},
  {char: 'ز', english: 'z', ipa:'z'},
  {char: 'د', english: 'd', ipa:'d'},
  {char: 'ذ', english: 'dh', ipa:'ð'},
  {char: 'ط', english: 't (backed)', ipa:'t_glottal'},
  {char: 'ظ', english: 'dh (backed)',ipa:'ð_glottal'},
  {char: 'صص / ص', english: 's (backed)',ipa:'s_glottal'},
  {char: 'ضض / ض', english: 'd (backed)',ipa:'d_glottal'},
  {char: 'ععع / ع', english: 'a (backed)',ipa:'a_glottal'},
  {char: 'غغغ / غ', english: 'gh (backed)',ipa:'ʁ_glottal'}];

export default arabic;
