const cyrillic = [
  {char: 'Е', english: 'ye',ipa:'ye'},
  {char: 'А', english: 'a',ipa:'a'},
  {char: 'О', english: 'o/ah',ipa:'o'},
  {char: 'Ю', english: 'yu',ipa:'yu'},
  {char: 'Ё', english: 'yo',ipa:'yo'},
  {char: 'Ь', english: 'silent'},
  {char: 'Ы', english: 'short i',ipa:'ɪ'},
  {char: 'Я', english: 'ya',ipa:'ya'},
  {char: 'И', english: 'i',ipa:'i'},
  {char: 'Й', english: 'short i',ipa:'ɪ'},
  {char: 'У', english: 'between u and i',ipa:'y'},
  {char: 'Э', english: 'e',ipa:'e'},
  {char: 'В', english: 'v',ipa:'v'},
  {char: 'Г', english: 'g',ipa:'g'},
  {char: 'Д', english: 'd',ipa:'d'},
  {char: 'Ж', english: 'zh',ipa:'ʒ'},
  {char: 'З', english: 'z',ipa:'z'},
  {char: 'Р', english: 'r',ipa:'r'},
  {char: 'С', english: 's',ipa:'s'},
  {char: 'Т', english: 't',ipa:'t'},
  {char: 'Ф', english: 'f',ipa:'f'},
  {char: 'Х', english: 'kh',ipa:'x'},
  {char: 'Ц', english: 'ts',ipa:'ts'},
  {char: 'Ч', english: 'ch',ipa:'tʃ'},
  {char: 'Ш', english: 'sh',ipa:'ʃ'},
  {char: 'Щ', english: 'shch',ipa:'ʃtʃ'},
  {char: 'Б', english: 'b',ipa:'b'},
  {char: 'Џ', english: 'dzh',ipa:'dʒ'},
  {char: 'К', english: 'k',ipa:'k'},
  {char: 'Л', english: 'l',ipa:'l'},
  {char: 'М', english: 'm',ipa:'m'},
  {char: 'Н', english: 'n',ipa:'n'},
  {char: 'П', english: 'p',ipa:'p'}];

export default cyrillic;
