const ipa = [{char: 'i', english: 'ee', ipa: 'i'},
{char: 'y', english: 'fronted u', ipa: 'y'},
{char: 'ɪ', english: 'short i', ipa: 'ɪ'},
{char: 'ʏ', english: 'short IPA y', ipa: 'ʏ'},
{char: 'ɨ', english: 'neutralized ee', ipa: 'ɨ'},
{char: 'ʉ', english: 'neutralized oo', ipa: 'ʉ'},
{char: 'ɯ', english: 'unrounded oo', ipa: 'ɯ'},
{char: 'u', english: 'oo', ipa: 'u'},
{char: 'ʊ', english: 'oo in wood', ipa: 'ʊ'},
{char: 'e', english: 'e sound in play', ipa: 'e'},
{char: 'ø', english: 'rounded IPA o', ipa: 'ø_'},
{char: 'ɘ', english: 'Australian i in bird', ipa: 'ɘ'},
{char: 'ɵ', english: 'rounded ɘ', ipa: 'ɵ'},
{char: 'ɤ', english: 'unrounded o', ipa: 'ɤ'},
{char: 'o', english: 'o in ohm', ipa: 'o'},
{char: 'ɛ', english: 'e in sped', ipa: 'ɛ'},
{char: 'œ', english: 'rounded ɛ', ipa: 'œ'},
{char: 'ɜ', english: 'British i in bird', ipa: 'ɜ'},
{char: 'ɞ', english: 'rounded ɜ', ipa: 'ɞ'},
{char: 'ʌ', english: 'u in but', ipa: 'ʌ'},
{char: 'ɔ', english: 'o in for', ipa: 'ɔ'},
{char: 'æ', english: 'a in sat', ipa: 'æ'},
{char: 'ɐ', english: 'Scottish a in stack', ipa: 'ɐ'},
{char: 'a', english: 'a sound in thigh', ipa: 'a'},
{char: 'ɶ', english: 'rounded IPA a', ipa: 'ɶ'},
{char: 'ɑ', english: 'a in father', ipa: 'ɑ'},
{char: 'ɒ', english: 'rounded ɑ', ipa: 'ɒ'},
{char: 'p', english: 'p', ipa: 'p'},
{char: 'b', english: 'b', ipa: 'b'},
{char: 't', english: 't', ipa: 't'},
{char: 'd', english: 'd', ipa: 'd'},
{char: 'ʈ', english: 't with curled tongue', ipa: 'ʈ'},
{char: 'ɖ', english: 'd with curled tongue', ipa: 'ɖ'},
{char: 'c', english: 'fronted k', ipa: 'c'},
{char: 'ɟ', english: 'voiced IPA c', ipa: 'ɟ'},
{char: 'k', english: 'k', ipa: 'k'},
{char: 'g', english: 'g', ipa: 'g'},
{char: 'q', english: 'uvular k', ipa: 'q'},
{char: 'ɢ', english: 'voiced IPA q', ipa: 'ɢ'},
{char: 'ʔ', english: 'first h in uh-oh', ipa: 'ʔ'},
{char: 'm', english: 'm', ipa: 'm'},
{char: 'ɱ', english: 'm with your top teeth', ipa: 'ɱ'},
{char: 'n', english: 'n', ipa: 'n'},
{char: 'ɳ', english: 'n with curled tongue', ipa:  'ɳ'},
{char: 'ɲ', english: 'nyeh', ipa: 'ɲ'},
{char: 'ŋ', english: 'ng in going', ipa: 'ŋ'},
{char: 'ɴ', english: 'uvular ŋ', ipa: 'ɴ'},
{char: 'ʙ', english: 'flapping lips', ipa: 'ʙ'},
{char: 'r', english: 'rolled r', ipa: 'r'},
{char: 'ʀ', english: 'rolled uvular r', ipa: 'ʀ'},
{char: 'ⱱ', english: 'tap of teeth on lips', ipa: 'ⱱ'},
{char: 'ɾ', english: 'tt in setting', ipa: 'ɾ'},
{char: 'ɽ', english: 'ɾ with curled tongue', ipa: 'ɽ'},
{char: 'ɸ', english: 'f without teeth', ipa: 'ɸ'},
{char: 'β', english: 'v without teeth', ipa: 'β'},
{char: 'f', english: 'f', ipa: 'f'},
{char: 'v', english: 'v', ipa: 'v'},
{char: 'θ', english: 'th in think', ipa: 'θ'},
{char: 'ð', english: 'th in this', ipa: 'ð'},
{char: 's', english: 's', ipa: 's'},
{char: 'z', english: 'z', ipa: 'z'},
{char: 'ʃ', english: 'sh', ipa: 'ʃ'},
{char: 'ʒ', english: 's in pleasure', ipa: 'ʒ'},
{char: 'ʂ', english: 's with curled tongue', ipa: 'ʂ'},
{char: 'ʐ', english: 'z with curled tongue', ipa: 'ʐ'},
{char: 'ç', english: 'fronted kh', ipa: 'ç'},
{char: 'ʝ', english: 'voiced ç', ipa: 'ʝ'},
{char: 'x', english: 'scottish ch', ipa: 'x'},
{char: 'ɣ', english: 'voiced x', ipa: 'ɣ'},
{char: 'χ (long x)', english: 'uvular x', ipa: 'longx'},
{char: 'ʁ', english: 'French r', ipa: 'ʁ'},
{char: 'ħ', english: 'h with your throat constricted', ipa: 'ħ'},
{char: 'ʕ', english: 'voiced ħ', ipa: 'ʕ'},
{char: 'h', english: 'h', ipa: 'h'},
{char: 'ɦ', english: 'hard h', ipa: 'ɦ'},
{char: 'ɬ', english: 'voiceless l with teeth on tongue', ipa: 'ɬ'},
{char: 'ɮ', english: 'voiced ɬ', ipa: 'ɮ'},
{char: 'ʋ', english: 'v without touching lips', ipa: 'ʋ'},
{char: 'ɹ', english: 'r', ipa: 'ɹ'},
{char: 'ɻ', english: 'r with curled tongue', ipa: 'ɻ'},
{char: 'j', english: 'y in yes', ipa: 'j'},
{char: 'ɰ', english: 'backed j', ipa: 'ɰ'},
{char: 'l', english: 'l', ipa: 'l'},
{char: 'ɭ', english: 'l with curled tongue', ipa: 'ɭ'},
{char: 'ʎ', english: 'j with sides of tongue', ipa: 'ʎ'},
{char: 'ʟ', english: 'backed ʎ', ipa: 'ʟ'},
{char: 'w', english: 'w', ipa: 'w'},
{char: 'ʍ', english: 'voiceless w', ipa: 'ʍ'},
{char: 'ɥ', english: 'fronted w', ipa: 'ɥ'},
{char: 'ɕ', english: 'ʃ with flat of tongue', ipa: 'ɕ'},
{char: 'ʑ', english: 'ʒ with flat of tongue', ipa: 'ʑ'},
{char: 'ɧ', english: 'ʃ and x at the same time', ipa: 'ɧ'}
];

export default ipa;
