const persian = [
  {char: 'ا', english: 'a', ipa:'a'},
  {char: 'یی / ی', english: 'ee', ipa:'i'},
  {char: 'و', english: 'o/u',ipa:'u'},
  {char: 'ء', english: 'glottal stop', ipa: 'ʔ'},
  {char:'ههه / ه', english: 'h',ipa:'h'},
  {char: 'ببب / ب', english: 'b',ipa:'b'},
  {char: 'پپ / پ', english: 'p', ipa: 'p'},
  {char: 'تتت / ت', english: 't', ipa:'t'},
  {char: 'ننن / ن', english: 'n',ipa:'n'},
  {char: 'ثث / ث', english: 's', ipa: 's'},
  {char: 'ٖسس / س', english: 's', ipa:'s'},
  {char: 'شش / ش', english: 'sh',ipa:'ʃ'},
  {char: 'حح / ح', english: 'hard h', ipa:'ɦ'},
  {char: 'خخ / خ', english: 'kh', ipa:'x'},
  {char: 'جج / ج', english: 'j', ipa:'dʒ'},
  {char: 'چچ / چ', english: 'ch', ipa: 'tʃ'},
  {char: 'مم / م', english: 'm', ipa:'m'},
  {char: 'فف / ف', english: 'f', ipa:'f'},
  {char: 'قق / ق', english: 'gh', ipa:'ʁ'},
  {char: 'ک', english: 'k', ipa:'k'},
  {char: 'گ', english: 'g', ipa: 'g'},
  {char: 'لل / ل', english: 'l', ipa:'l'},
  {char: 'ر', english: 'r', ipa:'r'},
  {char: 'ز', english: 'z', ipa:'z'},
  {char: 'ژ', english: 's in pleasure', ipa: 'ʒ'},
  {char: 'د', english: 'd', ipa:'d'},
  {char: 'ذ', english: 'z', ipa:'z'},
  {char: 'ط', english: 't', ipa:'t'},
  {char: 'ظ', english: 'z',ipa:'z'},
  {char: 'صص / ص', english: 's',ipa:'s'},
  {char: 'ضض / ض', english: 'z',ipa:'z'},
  {char: 'ععع / ع', english: 'glottal stop and a',ipa:'a'},
  {char: 'غغغ / غ', english: 'uvular k',ipa:'q'}];

export default persian;
